version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: apartment_db
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: apartment_db
      DB_PORT: 3306
      PORT: 3000
    command: ["sh", "-c", "npx wait-port db:3306 && npm run setup"]

volumes:
  db-data:

